name: Force to Sync
on:
  workflow_dispatch:
jobs:
  sync-force:
    uses: WillBooster/reusable-workflows/.github/workflows/sync.yml@main
    with:
      sync_params_without_dest: '--force -v --tag-version'
    secrets:
      DEST_GIT_URL: https://oauth2:${{ secrets.PUBLIC_GH_BOT_PAT }}@github.com/WillBooster/sample-of-one-way-git-sync
