name: Sync

on:
  release:
    types: [published]

jobs:
  sync:
    uses: WillBooster/reusable-workflows/.github/workflows/sync.yml@main
    with:
      non_self_hosted: true
      sync_params_without_dest: 'sync -v --tag-version -p https://github.com/WillBooster/one-way-git-sync/commits/'
    secrets:
      DEST_GIT_URL: https://oauth2:${{ secrets.PAT_FOR_TEST }}@github.com/WillBooster/sample-of-one-way-git-sync
